config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  get "/profile", to: "users#show"
  get "/invite", to: "users#invite"
  get "/send_invite", to: "users#send_invite"

  get "/calculate_score", to: "games#calculate_score"
  resources :games, except: [:edit, :update]

  namespace :games do
    get "/:id/end", to: "end#show"
  end

  mount Sidekiq::Web => '/sidekiq'

  # Routes for Google authentication
  get "/auth/:provider/callback", to: "sessions#googleAuth"
  get "/auth/failure", to: redirect("/")


  delete "/profile", to: "games_score#destroy"

  resources :games, only:[:index, :destroy]

end

app/models/game.rb
class Game < ApplicationRecord
  validates_presence_of :category, :difficulty, :number_of_questions, :custom_name
  belongs_to :user
  has_many :game_score, dependent: :destroy
end

app/controllers/games/end_controller.rb
class Games::EndController < ApplicationController
  before_action :require_user
  
  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/games/stats_controller.rb
class Games::StatsController < ApplicationController
  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_user
  def new
  end

  def index
    @user = current_user
    @games = current_user.games
  end

  def create
    game = current_user.games.create(game_params)
    if game.save
      redirect_to "/games"
    else
      flash[:error] = game.errors.full_messages.to_sentence
      redirect_to "/games/new"
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end

  def show
    facade = GamesFacade.new(current_user, params[:id])

    render locals: {
      game_id: params[:id],
      questions: facade.questions,
      total_questions: facade.number_of_questions
    }
  end

  def calculate_score
    if params["question"].nil?
      flash[:error] = "Please answer all questions"
      redirect_to "/games/#{params["game_id"].to_i}" and return
    end

    number_correct = params["question"].values.count {|value| value == "true"}
    game_score = GameScore.create(user_id: current_user.id, game_id: params["game_id"].to_i, score: number_correct)
    total_questions = game_score.game.number_of_questions

    if game_score.game_percent_score == 0
      flash[:error] = "You got #{number_correct} correct answers! Please try again."
    elsif game_score.game_percent_score < 50.0
      flash[:success] = "You got #{number_correct} correct answers out of #{total_questions}! Good try. Just remember, the more you know the more you grow!"
    else
      flash[:success] = "You got #{number_correct} correct answers out of #{total_questions}!!! You're ripe with knowledge!"
    end
    redirect_to "/games/#{params["game_id"].to_i}/end"
  end

  private
  def game_params
    params.permit(:custom_name, :number_of_questions, :category, :difficulty)
  end
end

app/views/games/index.html.erb
<div class="container">
  <center><h2><%= @user.username %>'s Games</h2></center>
  <br>
  <center><%= link_to "Create New Game", "/games/new", class: 'new-game-btn zoom btn btn-light' %></center>
  <br>
  <br>
  <% unless @games.empty? %>
    <section class="games">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Game</th>
            <th scope="col">Category</th>
            <th scope="col">Difficulty</th>
            <th scope="col">Total Questions</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
            <% @games.each do |game| %>
              <section id='game-<%= game.id %>'>
                  <tr>
                    <td><%= game.custom_name %></td>
                    <td><%= game.category %></td>
                    <td><%= game.difficulty %></td>
                    <td><%= game.number_of_questions %></td>
                    <td>
                      <p><%= button_to "Start Game", game_path(id: game.id), {method: :get, class: 'btn btn-info'} %></p>
                      <p><%= button_to "Delete", game_path(id: game.id), {method: :delete, class: 'btn btn-danger'} %></p>
                  </tr>
              </section>
            <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</div>

app/views/games/new.html.erb
<h1 class='display-3' align='center'> Create a Game! </h1>

<center>
  <%= form_tag "/games", method: :post do %>
    <%= label_tag "Custom name:" %>
    <%= text_field_tag :custom_name, nil, placeholder: "Name" %> <br>
    <%= label_tag "Total Number of Trivia Questions:" %>
    <%= select_tag(:number_of_questions, options_for_select(questions), {class: "select-field"}) %><br>
    <%= label_tag "Trivia Category:" %>
    <%= select_tag(:category, options_for_select(categories), {class: "select-field"}) %><br>
    <%= label_tag "Trivia Difficulty:" %>
    <%= select_tag(:difficulty, options_for_select(difficulties), {class: "select-field"}) %><br>
    <%= submit_tag('Create Game', class: "button") %>
  <% end %>
</center>

app/views/games/score.js.erb
$(document).ready(function(){
  var user_answer = document.querySelector('.option').checked;
  $(".next-btn").click(function(e) {
    e.preventDefault();
    debugger;
    console.log(user_answer)
  });
});

app/views/games/show.html.erb
<script src="https://code.responsivevoice.org/responsivevoice.js"></script>
<center>
  <input value='Play Game' onclick="responsiveVoice.speak(document.getElementById('question-0').textContent);" type='button' class='btn btn-success' data-toggle='modal' data-target='#myModal-0' />
</center>

<%= form_with(url: "/calculate_score", method: :get) do  %>
<input type="hidden" id="game_id" name="game_id" value="<%= game_id %>" />
  <% questions.each_with_index do |question, index| %>
  <div class="modal" id="myModal-<%= index %>" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
    <div class="modal-dialog">

        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="mainModalLabel">
              Question <%= index + 1 %> of <%= total_questions %>
            </h4>
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          </div>
          <p class='question' id='question-<%= index %>'><%= question.question %></p>
          <hr>
          <ul>
          <% question.options.each_with_index do |option, index|  %>
            <p id='option-<%= index + 1 %>'>
              <%= radio_button_tag("question[#{question.id}]", question.correct_answer==option) %> <%= option %>
            </p>
          <% end %>
          </ul>
          <hr />
          <% if (index + 1) == total_questions %>
            <%= submit_tag "Submit", {class: 'btn btn-primary btn-lg btn-block'} %>
          <% else %>
            <input value='Next' onclick="responsiveVoice.speak(document.getElementById('question-<%= index + 1 %>').textContent);" type='button' class="next-btn btn btn-primary btn-lg btn-block" data-dismiss='modal' data-toggle='modal' data-target='#myModal-<%= index + 1 %>' />
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>